language: ruby
sudo: false

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-19mode # JRuby in 1.9 mode

script: bundle exec rake

gemfile:
  - gemfiles/activesupport_5.1.gemfile
  - gemfiles/activesupport_5.2.gemfile

matrix:
  fast_finish: true
